### ISSUE TITLE
indexing cabal sandbox

### ISSUE THREAD

**Issue by dontdieych** [bgamari/hoogle-index#1]
Is hoogle-index capable of sandbox installed packages?

**Comment by yfyf** [comment]
Uhm, so since #7 is merged, I guess this can be closed? I just tried doing `hoogle-index -l` in a sandbox and although along the way it had quite a few errors, it did build the index and seems to actually work. So at least some basic support for cabal sandboxes is in place, if there are bugs / TODOs re this, they can be handled in more specific issues probably.

Anyway, thanks for the package, I was always missing something like this.

A sample for some of the errors:

```
<..>
Error while indexing haskell2010: Can't build documentation for haskell2010

Error while indexing haskell98: Can't build documentation for haskell98

Looking for /usr/share/doc/libghc-parallel-doc/html/parallel.txt
Downloading parallel-3.2.0.4...
Unpacking to parallel-3.2.0.4/
cabal: 'require-sandbox' is set to True, but no sandbox is present.
Error while indexing parallel: Process cabal failed with error 1
<..>
```

The last one is obviously specific to my cabal config, but you might still want to be aware of it.

**Comment by bgamari** [comment]
Indeed this is fixed. Thanks for bringing this to my attention.
